#TEST REQUESTS


###Create User
POST http://localhost:3000/user
Content-Type: application/json

{
    "firstName":"Bandana",
    "lastName":"Jaishi",
    "email":"arjun@ggmail.com",
    "phone":"9765424189",
    "password":"Arjun123"
}


### USER LOGIN

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"a.jaishi@gmail.com",
    "password":"Arjun123"
}

### FIND BY ID
GET http://localhost:3000/user/6489fc9bbac28be5cdc2ae29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODlmYzliYmFjMjhiZTVjZGMyYWUyOSIsImlhdCI6MTY4Njk5Njc1NywiZXhwIjoxNjg2OTk2Nzg3fQ.hB6igsVQzg4TbUKSKbhCMF3hjRrK0D4DEiQz4B9MZZo


###
GET http://localhost:3000/user


### FIND USER BY QUERY VALUE
GET http://localhost:3000/users?id=6485b9937aa9ace5003b899b


### DELETE USER

DELETE http://localhost:3000/user/6485ba287aa9ace5003b899f


### UPDATE USER
PUT http://localhost:3000/user/6485b9937aa9ace5003b899b
Content-Type: application/json

{
    "firstName":"ArjunJ",
    "lastName":"Raj"
}



###REFRESH TOKEN
POST http://localhost:3000/refreshToken
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODlmYzliYmFjMjhiZTVjZGMyYWUyOSIsImlhdCI6MTY4Njk5Njc5NSwiZXhwIjoxNzE4NTU0Mzk1fQ.zXs17M1LJd7BBAzBA8_r09U4sbm9UrmvCFVyleI66Lc"
}